### PR TITLE
Fix not returning all sizeshape features

### PR DESCRIPTION
**Pull request by alxndrkalinin**
Current version does not return all sizeshape features because [some](https://github.com/afermg/cp_measure/blob/d11ea614ed7f0d2aa0d40a3501b33a75ce97f581/src/cp_measure/fast/measureobjectsizeshape.py#L437C9-L437C27) of them are never merged into the final [results](https://github.com/afermg/cp_measure/blob/d11ea614ed7f0d2aa0d40a3501b33a75ce97f581/src/cp_measure/fast/measureobjectsizeshape.py#L518) dict:

```
import numpy as np
from cp_measure.bulk import get_fast_measurements

measurements = get_fast_measurements()

size = 200
rng = np.random.default_rng(42)
pixels = rng.integers(low=0, high=10, size=(size, size))

masks = np.zeros_like(pixels)
masks[5:-6, 5:-6] = 1
print(np.unique([k.split("_")[0] for k in  measurements["sizeshape"](masks, pixels).keys()]))

> ['CentralMoment' 'HuMoment' 'InertiaTensor' 'InertiaTensorEigenvalues'
 'NormalizedMoment' 'SpatialMoment']
```

After fix:

```
 print(np.unique([k.split("_")[0] for k in  measurements["sizeshape"](masks, pixels).keys()]))

> ['Area' 'BoundingBoxArea' 'BoundingBoxMaximum' 'BoundingBoxMinimum'
 'Center' 'CentralMoment' 'Compactness' 'ConvexArea' 'Eccentricity'
 'EquivalentDiameter' 'EulerNumber' 'Extent' 'FilledArea' 'FormFactor'
 'HuMoment' 'InertiaTensor' 'InertiaTensorEigenvalues' 'MajorAxisLength'
 'MaximumRadius' 'MeanRadius' 'MedianRadius' 'MinorAxisLength'
 'NormalizedMoment' 'Orientation' 'Perimeter' 'PerimeterCrofton'
 'Solidity' 'SpatialMoment']
```

Other small fixes:
- moved spacing to arguments because [objects](https://github.com/afermg/cp_measure/blob/d11ea614ed7f0d2aa0d40a3501b33a75ce97f581/src/cp_measure/fast/measureobjectsizeshape.py#L543) is not defined
- remove 2d specific features from [desired_properties](https://github.com/afermg/cp_measure/blob/d11ea614ed7f0d2aa0d40a3501b33a75ce97f581/src/cp_measure/fast/measureobjectsizeshape.py#L383)
- allow [calculate_advanced](https://github.com/afermg/cp_measure/blob/d11ea614ed7f0d2aa0d40a3501b33a75ce97f581/src/cp_measure/fast/measureobjectsizeshape.py#L394) for 3D, which is supported for them

### CODE REVIEW

**Comment by afermg** [comment]
Thanks for the PR! I chatted with @gnodar01, and while we agree that new features are better, we will want to first incorporate this into CellProfiler 5 before changing the output. 

-I will edit your PR to add these 'new features' as an optional flag, true by default. That way cp_measure users can get as many features as possible but we will not break (too many) CellProfiler pipelines. 
- Once it is integrated in CellProfiler and accounted for in tests we will remove the flag and put it in.

**Comment by afermg** [comment]
Side-note, area-filled is set as 'desired-property' but I presume it is only relevant for 2d? Please do correct me if I'm wrong. I will adjust the code for it to be only added for 2D images/masks.

**Comment by alxndrkalinin** [comment]
Yea `area_filled` works for both 2d and 3d

**Comment by alxndrkalinin** [comment]
I fixed and tested 3d features, all seems to work okay now. Not sure if CP4 was returning all kinds of moment features, feel free to move to new category if this is not backwards compatible.

**Comment by afermg** [comment]
Ok, that should cover it. Could you check if it still works for you? Also, if you could point me towards the code you are using for this that'd be great so I can write 3D tests, which is not currently covered. In the meantime, if this works for you I will merge and release the upper bounds for skimage.

**Comment by alxndrkalinin** [comment]
Just removed moments Hu for 3d, they're 2d only. Otherwise, good to merge and release!

Here's my genius testing code for 3d, behold 😂

```python
import numpy as np
from cp_measure.bulk import get_fast_measurements

measurements = get_fast_measurements()

size = 200
rng = np.random.default_rng(42)
pixels = rng.integers(low=0, high=10, size=(size, size, size))

masks = np.zeros_like(pixels)
masks[5:-6, 5:-6, :] = 1
print(np.unique([k.split("_")[0] for k in  measurements["sizeshape"](masks, pixels).keys()]))
```

**Pull request merged**
